class BatamiaouGame:
    def __init__(self, seed: int | None = None) -> None: ...
    def reset(self, seed: int | None = None) -> None: ...
    def deck(self) -> bytes: ...
    def play(self) -> None: ...
    def run(self) -> int: ...
