class BatamiaouGame:
    def __init__(self, seed: int | None = None) -> None: ...
    def reset(self, seed: int | None = None) -> None: ...
    def deck(self) -> bytes: ...
    def play(self) -> int | None: ...
    def run(self) -> int | None: ...
    def mask_deck(self, mask: int) -> int: ...
